"""El catálogo de TODO lo que se investiga: temas por bloques y series por bloques.
Lo usa armar_kit.py. Para añadir algo, se añade una línea aquí y se corre armar_kit.py.
"""

# ── TEMAS: (tema, qué abarca). La letra del bloque da el código: A01, A02…
TEMAS = {
    "A · Diseño visual e imagen": [
        ("Texturas", "bancos gratis (Poly Haven, ambientCG, otros), texturas de papel, tinta, tela, metal, madera, grano; escanear o fotografiar las propias; cómo aplicarlas en Photoshop, Blender y HTML"),
        ("Tipografías", "fuentes libres por estilo (manga, cómic, retro, cyberpunk, gótico, fantasía, caligrafía, pixel), cuáles traen tildes, ñ, ¿ y ¡, cómo editarlas o crear una (FontForge), cómo combinarlas, licencias"),
        ("Rotulación y letras dibujadas", "lettering de manga y cómic, onomatopeyas, rótulos pintados, letra a mano digital; herramientas (Clip Studio, Procreate, Illustrator, Krita) y cómo imitar el estilo de cada serie"),
        ("Fondos y paisajes", "cómo se pintan los fondos de anime (estudios de fondos, Kusanagi, Makoto Shinkai), fotobash, fondos 3D pintados, fondos de pantalla oficiales y de artistas, dónde encontrarlos en alta"),
        ("Color, luz y paletas", "teoría práctica, paletas de series y películas, luz de color, atmósfera, hora del día; herramientas de paletas y tableros de estética (Pinterest, ArtStation)"),
        ("Fusionar estilos y crear algo nuevo", "cómo mezclan estilos los diseñadores (collage, técnica mixta, Spider-Verse, Arcane) sin copiar; ejercicios para sacar un estilo propio"),
        ("Diseño que no parece hecho por IA", "los rasgos que delatan una imagen de IA y cómo evitarlos: imperfección intencional, textura real, composición con intención, tipografía cuidada"),
        ("Composición para láminas, banners y pósters", "jerarquía, lectura, ritmo, espacio; cómo se ve en el móvil; plantillas de pósters de cine, anime y videojuegos"),
        ("Edición de imagen profesional", "Photoshop, GIMP, Krita, Photopea y alternativas: flujos, atajos, capas de ajuste, máscaras, plugins gratis"),
        ("Cuadros de diálogo, HUD e interfaces", "globos de manga, cartelas, subtítulos, menús y HUD de videojuegos y series; cómo replicarlos en HTML, Photoshop o Blender"),
    ],
    "B · Personajes: recortar, posar, integrar": [
        ("Recortar personajes sin halo", "comparar ToonOut, BiRefNet, anime-segmentation, Photoshop, Canva y See-through para ilustraciones y fotogramas; pelo suelto y líneas finas; limpiar bordes"),
        ("Ampliar imágenes sin perder calidad", "Real-ESRGAN, waifu2x, Upscayl y otros: cuál para anime, para fotos, para texto; límites en 8 GB"),
        ("Dar una pose nueva a un personaje", "ControlNet y OpenPose, maniquíes 3D (Magic Poser, Design Doll, Blender), referencias de pose; mantener cara y ropa"),
        ("Personajes consistentes con IA", "LoRA de personaje, IP-Adapter, referencias de estilo, mismo rostro y vestuario en varias escenas; qué se puede hacer en local"),
        ("Integrar un personaje en un fondo", "luz y sombra de contacto, luz de borde, igualar color y grano, profundidad, algo delante; la composición final (satsuei) de los estudios de anime"),
        ("Luces, sombras, tinta y color en anime", "cel shading, grosor de línea, colores de sombra, brillos; cómo imitar el acabado de cada estudio (Ufotable, MAPPA, Trigger, Kyoto Animation, Ghibli)"),
        ("Diseño de personajes y vestuario", "hojas de modelo, vistas de frente, perfil y espalda, cómo se diseñan trajes y accesorios, siluetas reconocibles"),
    ],
    "C · VTubers": [
        ("Programas de VTuber", "VTube Studio, Live2D Cubism, VSeeFace, Warudo, VNyan, Veadotube (PNGTuber), VRoid y modelos 3D: comparativa, precios, qué corre en su PC"),
        ("Capas y preparación del arte", "cómo se parte un dibujo en capas para Live2D, orden, nombres, qué se separa; separar con IA (See-through y alternativas)"),
        ("Rigging en Cubism FREE", "cintura, brazos, pelo, física, parpadeo, boca, expresiones, dentro de los límites gratis (100 mallas, 30 partes, 30 parámetros)"),
        ("Seguimiento y configuración", "webcam o iPhone, VBridger, sincronía de labios, calibración, atajos, objetos y expresiones en VTube Studio"),
        ("Overlays y escena de directo", "OBS, marcos, alertas, chat en pantalla, animaciones, widgets (StreamElements y otros), transiciones"),
        ("Diseñadores y riggers", "dónde se encarga un modelo (VGen, Skeb, Twitter), precios, cómo pedir un buen encargo, derechos"),
        ("Generadores e IA para VTubers", "generar el diseño, las expresiones y la voz; herramientas nuevas de 2026"),
        ("VTubers hispanos que funcionan", "qué hacen, tipo de contenido, horarios, cómo crecieron, comunidades"),
    ],
    "D · Voz, doblaje y guion": [
        ("Técnica de doblaje", "sincronía labial, interpretación, respiración, esfuerzos y gritos, cuidar la voz"),
        ("Escribir guiones", "guiones para fandub, animación, radio y video corto: formato, ritmo, humor, diálogos naturales"),
        ("Traducir y adaptar guiones", "ajuste para doblaje, localización, modismos neutros para Latinoamérica"),
        ("Adaptar canciones al español", "métrica, rima, acentos, que se pueda cantar; cómo lo hacen los adaptadores profesionales de anime y Disney"),
        ("Voz con IA (texto a voz y clonación)", "servicios y modelos locales en 2026, calidad, idioma español, ética y consentimiento"),
        ("Cambiadores de voz en tiempo real", "RVC, VCClient y alternativas: calidad, latencia, uso en directo y en Discord"),
        ("Grabar en casa", "micrófonos por presupuesto, interfaz, tratamiento acústico barato, cadena de procesado"),
        ("Retos, ejercicios y tutoriales", "para una comunidad de doblaje y locución: por nivel, con devolución útil"),
        ("Locución profesional", "comercial, narración, audiolibro, radio; cómo conseguir trabajos, plataformas y tarifas"),
        ("Industria del doblaje latino", "estudios, escuelas y cursos por país (México, Argentina, Venezuela, Colombia, Chile, Perú), cómo entrar"),
    ],
    "E · Radio, TV y música": [
        ("Radios y televisores antiguos", "historia visual, modelos icónicos por década, materiales, sonido; cómo recrearlos en 3D y en diseño"),
        ("Radio en vivo online y en Discord", "producción, dos presentadores, bots de audio, derechos musicales, radios comunitarias que funcionan"),
        ("Letras de canciones en tiempo real", "karaoke, archivos LRC, APIs de letras sincronizadas, derechos"),
        ("Música, efectos y jingles libres", "bancos gratis, generadores, licencias para directos y videos"),
        ("Estética retro", "VHS, CRT, casete, vinilo, radio de válvulas: cómo se imita en diseño, video y sonido"),
    ],
    "F · Redes sociales (una por red)": [
        ("Instagram", "cómo crecer desde cero en 2026, algoritmo de Reels y del feed, horarios, hashtags, títulos, colaboraciones"),
        ("TikTok", "algoritmo, primeros segundos, formatos que funcionan, horarios, hashtags, sonidos, cómo evitar el bloqueo"),
        ("YouTube y Shorts", "algoritmo, miniaturas, títulos, retención, horarios, Shorts frente a largos, Content ID"),
        ("X (Twitter)", "algoritmo, comunidad de artistas y VTubers, horarios, hilos, etiquetas"),
        ("Facebook", "páginas y grupos, Reels, públicos por edad y país, negocios locales"),
        ("Reddit", "subreddits de anime, doblaje y arte, reglas, cómo participar sin que te borren"),
        ("Twitch y Kick", "empezar a transmitir, descubrimiento, categorías, horarios"),
        ("GitHub", "perfil, portafolio, proyectos abiertos, comunidad"),
        ("Automatizar redes legalmente", "APIs oficiales, programadores (Buffer, Metricool, Publer), qué se puede y qué no, límites"),
        ("Contenido de fandub y anime en redes", "derechos, Content ID, formatos que no bloquean, qué rinde en cada red"),
        ("Datos de horarios, hashtags y títulos", "tablas actualizadas por red y por país (Perú, México, Argentina, Colombia, España)"),
    ],
    "G · Discord al completo": [
        ("Cómo funciona Discord al completo", "permisos, roles, canales, foros, escenarios, onboarding, guía del servidor, AutoMod, apps, actividades, límites"),
        ("Bots y API de Discord", "bibliotecas, componentes nuevos, comandos, webhooks, hosting gratis, bots públicos que conviene usar"),
        ("Hacer crecer y moderar una comunidad", "eventos, retención, alianzas, listas de servidores, moderación sin estrés"),
        ("Diseño de servidores destacados", "banners, láminas, iconos, emojis, perfiles del servidor; ejemplos reales"),
    ],
    "H · Inteligencia artificial y herramientas": [
        ("Todos los programas de IA en 2026", "catálogo por categoría (texto, imagen, video, voz, música, 3D, código, agentes): gratis o de pago, local o en la nube"),
        ("Imagen con IA en una GPU de 8 GB", "ComfyUI, Flux, SDXL, modelos de anime, LoRAs, flujos listos"),
        ("Video con IA", "servicios y modelos locales, animar ilustraciones, coherencia entre planos"),
        ("Música y audio con IA", "generar música, separar pistas, limpiar voz, efectos"),
        ("3D con IA", "de imagen a modelo 3D, texturas generadas, cuándo sirve"),
        ("Textos que no parecen IA", "rasgos que delatan un texto de IA y cómo escribir con voz propia"),
        ("Agentes de IA", "Claude Code (Proyectos, subagentes), Codex, Antigravity, MCP: cómo coordinarlos, memoria, costos"),
        ("Skills de Claude", "las mejores, cuáles convienen para diseño, video y voz, cómo revisarlas antes de instalar"),
        ("Servidores MCP", "cuáles convienen, cuáles son gratis, seguridad"),
        ("Plugins de programas", "Photoshop, Premiere, After Effects, Blender, OBS y DaVinci: los mejores, gratis y de pago"),
    ],
    "I · Webs, programas y apps": [
        ("Diseño de páginas web", "tendencias 2026, cómo no parecer plantilla, referencias premiadas"),
        ("Optimizar y mejorar una web", "velocidad, SEO, accesibilidad, hosting gratis"),
        ("Apps para el celular", "Android con Kotlin, Flutter, React Native o PWA; publicar en Play Store; costos"),
        ("Programas y automatización en Windows", "Python, scripts, interfaces sencillas, empaquetar programas"),
    ],
    "J · Edición de video": [
        ("Premiere Pro", "flujos, atajos, plugins, plantillas"),
        ("DaVinci Resolve gratis", "edición, color, Fairlight, Fusion, límites de la versión gratis"),
        ("CapCut", "funciones, plantillas, qué es de pago, trucos para video corto"),
        ("After Effects y motion graphics", "animación de texto, efectos, alternativas gratis"),
        ("Recursos para editar", "overlays, efectos de sonido, LUTs, transiciones y plantillas gratis o baratas"),
        ("Editar para cada público", "qué ritmo, subtítulos y estilo gusta en Latinoamérica y en Asia"),
    ],
    "K · Negocio, estudios y dinero": [
        ("Negocios que funcionarían en Puno", "ideas realistas sin experiencia ni carrera, inversión inicial, casos reales de la región"),
        ("Presencia digital de la ladrillería", "Google Business, catálogo de WhatsApp, fotos de producto, anuncios locales"),
        ("Importar y vender en Perú", "courier, SUNAT, RUC y régimen, marketplaces, qué productos convienen"),
        ("Becas y cursos gratis", "Pronabec, Beca 18, becas de Japón (MEXT), Corea (GKS) y China (CSC), cursos gratis con certificado"),
        ("Ganar dinero con lo que ya sabe", "trabajo independiente en edición, diseño, voz y comunidades: plataformas y tarifas"),
        ("Precios regionales y descuentos legítimos", "licencias de estudiante y educativas, programas gratis en lugar de pago, qué cuesta menos en cada país de forma legal"),
    ],
    "L · Asia (personal)": [
        ("Apps para conocer gente de Asia", "China, Japón y Corea desde Latinoamérica: cuáles funcionan, seguridad, cómo presentarse"),
        ("Cómo llegar a ellos", "idioma básico, traducción en tiempo real, cultura, horarios, qué les interesa de Latinoamérica"),
        ("Redes asiáticas a fondo", "LINE, KakaoTalk, Xiaohongshu, Bilibili, Weibo, Douyin, note, Pixiv, Naver"),
        ("Mostrar Puno y el Titicaca", "fotos, poemas y voz para público asiático: qué engancha y dónde publicarlo"),
    ],
    "M · PC y Windows": [
        ("Optimizar la PC", "Windows 11, drivers de NVIDIA, RAM, disco; sin romper nada"),
        ("Personalizar el estilo de Windows", "Windhawk, Rainmeter, Wallpaper Engine, temas, iconos, cursores"),
        ("Programas gratis para todo", "alternativas gratuitas a los programas de pago más usados"),
    ],
    "N · Minecraft": [
        ("Mods y modpacks", "Forge, NeoForge y Fabric en 2026, los mejores packs, compatibilidad"),
        ("Rendimiento y servidores", "Voxy, Distant Horizons, C2ME, pregenerar, hosting barato"),
        ("Shaders, texturas y paquetes de recursos", "los mejores por estilo y cuánto piden a la PC"),
    ],
    "O · Videojuegos": [
        ("Estilos visuales de videojuegos", "cel shading, pixel art, low poly, pintado a mano, realismo: cómo se logra cada uno"),
        ("Interfaces de videojuegos", "HUD, menús y cuadros de diálogo como referencia de diseño"),
        ("Juegos que marcan tendencia", "los más jugados y comentados en 2026 y por qué"),
    ],
    "P · Recursos y comunidades": [
        ("Bancos gratis de todo", "imágenes, texturas, iconos, fuentes, sonidos, música y video, con su licencia"),
        ("Comunidades para aprender", "Discords, subreddits, foros y canales de cada tema de este catálogo, sobre todo en español"),
    ],
}

# ── SERIES nuevas (se suman a las de armar_kit.py). (serie, en qué fijarse, personajes)
SERIES = {
    "Anime de acción y fantasía épica": [
        ("Bungo Stray Dogs", "estilo, habilidades de nombre literario", "Dazai, Atsushi, Chuuya, Akutagawa"),
        ("Black Clover", "grimorios, magia y auras", "Asta, Yuno, Noelle, Yami"),
        ("Fire Force", "fuego, luz y efectos", "Shinra, Arthur, Maki, Benimaru"),
        ("Mashle", "comedia y magia", "Mash, Finn, Lance, Dot"),
        ("Wistoria: Wand and Sword", "academia de magia y torres", "Will, Elfaria"),
        ("Vinland Saga", "Inglaterra del siglo XI, paisajes y crudeza", "Thorfinn, Askeladd, Canute, Einar"),
        ("Demon Slayer: paisajes y auras", "los paisajes, las respiraciones y los efectos de Ufotable", "Tanjiro, Rengoku, Muichiro, Shinobu"),
        ("Solo Leveling: el Sistema y las sombras", "interfaces, sombras, mazmorras", "Jinwoo, Igris, Beru"),
    ],
    "Isekai y fantasía": [
        ("Mushoku Tensei", "mundo, magia y crecimiento", "Rudeus, Roxy, Eris, Sylphiette"),
        ("The Rising of the Shield Hero", "escudos, mundo y tono", "Naofumi, Raphtalia, Filo"),
        ("Overlord", "estética oscura, Nazarick", "Ainz, Albedo, Shalltear, Demiurge"),
        ("No Game No Life", "colores saturados y juegos", "Sora, Shiro, Stephanie, Jibril"),
        ("Sword Art Online (todas)", "interfaces de juego, mundos virtuales", "Kirito, Asuna, Sinon, Alice"),
        ("Saga of Tanya the Evil", "estética militar de entreguerras", "Tanya, Visha"),
        ("Tsukimichi: Moonlit Fantasy", "comedia isekai", "Makoto, Tomoe, Mio"),
        ("Konosuba", "comedia y explosiones", "Kazuma, Aqua, Megumin, Darkness"),
        ("Frieren: paisajes y memoria", "fondos, luz y melancolía", "Frieren, Fern, Stark, Himmel"),
    ],
    "Romance, drama y vida cotidiana": [
        ("Kaguya-sama: Love is War", "comedia y rótulos", "Kaguya, Shirogane, Chika"),
        ("The Apothecary Diaries (El diario de la boticaria)", "palacio chino, vestuario, misterio", "Maomao, Jinshi"),
        ("A Silent Voice (La chica sorda)", "lenguaje de señas, luz y emoción", "Shoko, Shoya"),
        ("Charlotte", "drama y giros", "Yu, Nao"),
        ("A Lull in the Sea (Nagi-Asu)", "mar, luz y pueblo", "Hikari, Manaka"),
        ("Blue Period", "pintura, arte y proceso", "Yatora, Yuka"),
        ("Bubble (Netflix)", "burbujas, parkour, color", "Hibiki, Uta"),
        ("Bocchi the Rock: bandas y bajones", "estilos cambiantes, conciertos", "Bocchi, Kita, Nijika, Ryo"),
    ],
    "Películas de anime y de estudio Ghibli": [
        ("El viaje de Chihiro", "fondos, baños, espíritus", "Chihiro, Haku, Yubaba, Sin Cara"),
        ("El castillo ambulante", "máquinas, campos, magia", "Howl, Sophie, Calcifer"),
        ("La princesa Mononoke", "el bosque, espíritus", "San, Ashitaka, Moro"),
        ("Your Name: cielos y ciudades", "cometas, Tokio, luz de Shinkai", "Taki, Mitsuha"),
        ("El estilo Ghibli en general", "cómo se logra: fondos pintados, comida, luz, viento", "—"),
    ],
    "Series animadas occidentales": [
        ("Hazbin Hotel y Helluva Boss", "estética, musical, radio demoníaca", "Charlie, Alastor, Angel Dust, Vaggie"),
        ("Steven Universe", "colores pastel, fusiones, música", "Steven, Garnet, Amatista, Perla"),
        ("Generator Rex", "nanitos, máquinas", "Rex, Six, Bobo"),
        ("Glitch Techs", "videojuegos que salen al mundo real", "Five, Miko"),
        ("Avatar y La leyenda de Korra", "los cuatro elementos, estilos de control, Ciudad República", "Aang, Zuko, Toph, Korra, Iroh"),
        ("Arcane y el arte de League of Legends", "pintura digital de Fortiche, splash arts", "Jinx, Vi, Jayce, Viktor, Ekko"),
        ("Invincible", "acción y contraste", "Mark, Omni-Man"),
        ("Castlevania", "gótico y acción", "Trevor, Sypha, Alucard"),
    ],
    "Películas y sagas": [
        ("Star Wars", "naves, sables, planetas, diseño de sonido", "Luke, Vader, Rey, Grogu"),
        ("Interstellar", "espacio, luz, música de Zimmer", "Cooper, Murph, TARS"),
        ("Spider-Verse: técnicas mixtas", "cómo se mezclan estilos en una película", "Miles, Gwen, Miguel"),
    ],
    "Videojuegos": [
        ("Cyberpunk 2077 (juego)", "Night City, interfaz, anuncios, neones", "V, Johnny Silverhand, Judy, Panam"),
        ("Watch Dogs 1, 2 y Legion", "hackeo, interfaces, ciudades", "Aiden, Marcus, DedSec"),
        ("The Last of Us", "naturaleza que invade, luz, silencio", "Joel, Ellie"),
        ("God of War (todas las sagas)", "mitología griega y nórdica", "Kratos, Atreus"),
        ("Hellblade", "sonido binaural, psicosis, niebla", "Senua"),
        ("A Plague Tale", "Francia medieval, ratas, luz", "Amicia, Hugo"),
        ("Days Gone", "moteros, bosques del noroeste", "Deacon"),
        ("Tomb Raider", "exploración, ruinas", "Lara Croft"),
        ("Little Nightmares", "horror de muñecos, escala", "Six, Mono"),
        ("Reanimal", "horror de Tarsier, islas y máscaras", "los dos hermanos"),
        ("No Man's Sky", "planetas de colores, portadas de ciencia ficción retro", "el viajero"),
        ("Elden Ring", "fantasía oscura, ruinas", "Melina, Malenia"),
        ("Final Fantasy VII", "Midgar, espadas, materia", "Cloud, Tifa, Aerith, Sephiroth"),
        ("Honkai: Star Rail", "interfaces y arte oficial", "March 7th, Kafka, el Trazacaminos"),
        ("Ghost of Tsushima", "viento, flores, samuráis", "Jin"),
    ],
    "Estética y referencias sueltas": [
        ("Tableros de Pinterest y estética", "cómo se arman tableros de referencia, estéticas populares (lo-fi, city pop, Y2K, cottagecore)", "—"),
        ("Cowboy Bebop: jazz y noir", "rótulos, jazz, color", "Spike, Faye, Jet, Ed"),
        ("Evangelion: tarjetas y NERV", "tipografía de tarjetas de título, interfaces", "Asuka, Shinji, Rei, Misato"),
    ],
}
